import type { Metadata } from "next";
import { Jost, Marcellus } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from '@/components/BootstrapClient.js';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Google fonts
const jost = Jost({
  variable: "--body-font",
  subsets: ["latin"],
  weight: ["400", "700"], // optional
});

const marcellus = Marcellus({
  variable: "--heading-font",
  subsets: ["latin"],
  weight: "400", // optional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} ${marcellus.variable} antialiased`}
      > 
        <Header />
        <main>{children}</main>
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
